#include <MKL25Z4.h>
#include "macros.h"

void initGPIO(void)
{
    SIM->SCGC5 |= ((SIM_SCGC5_PORTC_MASK) | (SIM_SCGC5_PORTE_MASK));

    PORTC->PCR[GC1] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC1] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC2] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC2] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC3] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC3] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC4] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC4] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC5] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC5] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC6] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC6] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC7] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC7] |= PORT_PCR_MUX(1);
    PORTC->PCR[GC8] &= ~PORT_PCR_MUX_MASK;
    PORTC->PCR[GC8] |= PORT_PCR_MUX(1);
    
    PORTE->PCR[RED] &= ~PORT_PCR_MUX_MASK;
    PORTE->PCR[RED] |= PORT_PCR_MUX(1);

    PTC->PDDR |= (MASK(GC1) | MASK(GC2) | MASK(GC3) | MASK(GC4) | MASK(GC5) | MASK(GC6) | MASK(GC7) | MASK(GC8));
    PTE->PDDR |= MASK(RED);
}