#include <MKL25Z4.h>
#include "macros.h"

void initPWM(void) {
    SIM_SCGC5 |= SIM_SCGC5_PORTA_MASK | SIM_SCGC5_PORTB_MASK | SIM_SCGC5_PORTD_MASK;

    PORTD->PCR[PTD3_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTD->PCR[PTD3_Pin] |= PORT_PCR_MUX(4);
    PORTA->PCR[PTA12_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTA->PCR[PTA12_Pin] |= PORT_PCR_MUX(4);
  
    PORTD->PCR[PTD0_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTD->PCR[PTD0_Pin] |= PORT_PCR_MUX(4);
     PORTD->PCR[PTD2_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTD->PCR[PTD2_Pin] |= PORT_PCR_MUX(4);  
  
    PORTD->PCR[PTD5_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTD->PCR[PTD5_Pin] |= PORT_PCR_MUX(4);
     PORTD->PCR[PTD1_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTD->PCR[PTD1_Pin] |= PORT_PCR_MUX(4);
  
    PORTB->PCR[PTB2_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTB->PCR[PTB2_Pin] |= PORT_PCR_MUX(3);
  PORTB->PCR[PTB3_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTB->PCR[PTB3_Pin] |= PORT_PCR_MUX(3);
    /*
    PORTA->PCR[PTA1_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTA->PCR[PTA1_Pin] |= PORT_PCR_MUX(4);
  PORTA->PCR[PTA2_Pin] &= ~PORT_PCR_MUX_MASK;
    PORTA->PCR[PTA2_Pin] |= PORT_PCR_MUX(4);*/
  
    SIM->SCGC6 |= SIM_SCGC6_TPM0_MASK | SIM_SCGC6_TPM1_MASK | SIM_SCGC6_TPM2_MASK ;
  
    SIM->SOPT2 &= ~SIM_SOPT2_TPMSRC_MASK;
    SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1);
  
    TPM0->MOD = 256;
    TPM1->MOD = 256;
    TPM2->MOD = 256;
    
    TPM0->SC &= ~((TPM_SC_CMOD_MASK) | (TPM_SC_PS_MASK));
    TPM0->SC |= (TPM_SC_CMOD(1) | TPM_SC_PS(4));
    TPM0->SC &= ~(TPM_SC_CPWMS_MASK);
    
    TPM1->SC &= ~((TPM_SC_CMOD_MASK) | (TPM_SC_PS_MASK));
    TPM1->SC |= (TPM_SC_CMOD(1) | TPM_SC_PS(7));
    TPM1->SC &= ~(TPM_SC_CPWMS_MASK);
    
    TPM2->SC &= ~((TPM_SC_CMOD_MASK) | (TPM_SC_PS_MASK));
    TPM2->SC |= (TPM_SC_CMOD(1) | TPM_SC_PS(4));
    TPM2->SC &= ~(TPM_SC_CPWMS_MASK);

    TPM0_C3SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM0_C3SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    TPM1_C0SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM1_C0SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    
    TPM0_C0SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM0_C0SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    TPM0_C2SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM0_C2SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    
    TPM0_C5SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM0_C5SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    TPM0_C1SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM0_C1SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    
    TPM2_C0SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM2_C0SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
    TPM2_C1SC &= ~((TPM_CnSC_ELSB_MASK) | (TPM_CnSC_ELSA_MASK) | (TPM_CnSC_MSB_MASK) | (TPM_CnSC_MSA_MASK));
    TPM2_C1SC |= (TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1));
}
